fixed empty and deplicate Breadcrumb in structured data
vtex-apps/structured-data pull request #74
Opened 2024-05-21 12:35 UTC by vivektam

2024-05-22 00:13 UTC, wender requested changes
Hi, thanks for the contribution! Can you please provide a Changelog?
[https://keepachangelog.com/en/1.0.0/](https://keepachangelog.com/en/1.0.0/)

2024-05-29 13:40 UTC, vivektam commented
Hi @wender I added the Changelog

2024-05-29 13:45 UTC, jorgeAcostaVTEX commented
Hi @vivektam I believe you tried to commit the changelog into the master branch instead of this one. Can you validate? 

<img width="1029" alt="image" src="https://github.com/vtex-apps/structured-data/assets/94565086/5200c50d-ed92-4da2-8404-b8baab7d7764">


Thanks!

2024-06-03 05:12 UTC, vivektam commented
Hi @jorgeAcostaVTEX  I did understand the point. I have pushed the changelog in my branch "structured-data"

2024-06-17 14:08 UTC, wender approved these changes

2024-06-17 14:10 UTC, merged